language: android
jdk:
- oraclejdk8

  # copied from https://github.com/oliexdev/openScale/blob/master/.travis.yml
env:
  global:
    - OWNER=${TRAVIS_REPO_SLUG%/*}
    - DEV=${OWNER/julio-b/dev}
    - BRANCH=${TRAVIS_BRANCH/master/}

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-build-tools-.+'

branches:
  except:
    - /^travis-.*-build$/
    - java-netselect

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.2"

before_script:
  - sed -i -r
    -e 's/applicationId "[^"]+/\0.'${DEV}'/'
    -e 's/(versionCode ).*/\1'$(date +%s)'/'
    -e 's/versionName "[^"]+/\0-'${DEV}'_'${TRAVIS_COMMIT:0:8}_$(date +%F)'/'
    app/build.gradle
  - sed -i -r
    -e 's/(<string name="app_name"[^>]*>[^<]+)/\1 ('${DEV}${BRANCH}')/'
    app/src/main/res/values/strings.xml
  # Create keystore by running:
  #   keytool -genkey -v -keystore debug.keystore -storepass android \
  #     -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 \
  #     -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
  #
  # Then base64 encode it with:
  #   base64 -w0 debug.keystore
  #
  # Then add this to Travis environment variables as DEBUG_KEYSTORE (make sure
  # not to enable displaying value in build logs)"
  - test -n "$DEBUG_KEYSTORE"
    && echo "$DEBUG_KEYSTORE" | base64 -d > $HOME/.android/debug.keystore
    || true

script: ./gradlew testDebug assembleAndroidTest assembleDebug

before_deploy:
  - ln -s app/build/outputs/apk/debug/app-debug.apk netselect-${DEV}${BRANCH}-build.apk
  - git tag -f travis-${DEV}${BRANCH}-build
  - git remote add gh
    https://${OWNER}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push gh :travis-${DEV}${BRANCH}-build || true
  - git push -f gh travis-${DEV}${BRANCH}-build
  - git remote remove gh

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: netselect-${DEV}${BRANCH}-build.apk
  skip_cleanup: true
  name: netselect development build (${TRAVIS_BRANCH})
  body: Automatic netselect development build of $TRAVIS_BRANCH
    ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
